/* $Id: cc_partner_states.sql,v 1.1 2003-05-19 20:33:15 juranj Exp $ */

INSERT INTO cc_partner_states VALUES ('AL','Alabama','S');
INSERT INTO cc_partner_states VALUES ('AK','Alaska','S');
INSERT INTO cc_partner_states VALUES ('AZ','Arizona','S');
INSERT INTO cc_partner_states VALUES ('AR','Arkansas','S');
INSERT INTO cc_partner_states VALUES ('CA','California','S');
INSERT INTO cc_partner_states VALUES ('CO','Colorado','S');
INSERT INTO cc_partner_states VALUES ('CT','Connecticut','S');
INSERT INTO cc_partner_states VALUES ('DE','Delaware','S');
INSERT INTO cc_partner_states VALUES ('DC','District of Columbia','S');
INSERT INTO cc_partner_states VALUES ('FL','Florida','S');
INSERT INTO cc_partner_states VALUES ('GA','Georgia','S');
INSERT INTO cc_partner_states VALUES ('HI','Hawaii','S');
INSERT INTO cc_partner_states VALUES ('ID','Idaho','S');
INSERT INTO cc_partner_states VALUES ('IL','Illinois','S');
INSERT INTO cc_partner_states VALUES ('IN','Indiana','S');
INSERT INTO cc_partner_states VALUES ('IA','Iowa','S');
INSERT INTO cc_partner_states VALUES ('KS','Kansas','S');
INSERT INTO cc_partner_states VALUES ('KY','Kentucky','S');
INSERT INTO cc_partner_states VALUES ('LA','Louisiana','S');
INSERT INTO cc_partner_states VALUES ('ME','Maine','S');
INSERT INTO cc_partner_states VALUES ('MD','Maryland','S');
INSERT INTO cc_partner_states VALUES ('MA','Massachusetts','S');
INSERT INTO cc_partner_states VALUES ('MI','Michigan','S');
INSERT INTO cc_partner_states VALUES ('MN','Minnesota','S');
INSERT INTO cc_partner_states VALUES ('MS','Mississippi','S');
INSERT INTO cc_partner_states VALUES ('MO','Missouri','S');
INSERT INTO cc_partner_states VALUES ('MT','Montana','S');
INSERT INTO cc_partner_states VALUES ('NE','Nebraska','S');
INSERT INTO cc_partner_states VALUES ('NV','Nevada','S');
INSERT INTO cc_partner_states VALUES ('NH','New Hampshire','S');
INSERT INTO cc_partner_states VALUES ('NJ','New Jersey','S');
INSERT INTO cc_partner_states VALUES ('NM','New Mexico','S');
INSERT INTO cc_partner_states VALUES ('NY','New York','S');
INSERT INTO cc_partner_states VALUES ('NC','North Carolina','S');
INSERT INTO cc_partner_states VALUES ('ND','North Dakota','S');
INSERT INTO cc_partner_states VALUES ('OH','Ohio','S');
INSERT INTO cc_partner_states VALUES ('OK','Oklahoma','S');
INSERT INTO cc_partner_states VALUES ('OR','Oregon','S');
INSERT INTO cc_partner_states VALUES ('PA','Pennsylvania','S');
INSERT INTO cc_partner_states VALUES ('RI','Rhode Island','S');
INSERT INTO cc_partner_states VALUES ('SC','South Carolina','S');
INSERT INTO cc_partner_states VALUES ('SD','South Dakota','S');
INSERT INTO cc_partner_states VALUES ('TN','Tennessee','S');
INSERT INTO cc_partner_states VALUES ('TX','Texas','S');
INSERT INTO cc_partner_states VALUES ('UT','Utah','S');
INSERT INTO cc_partner_states VALUES ('VT','Vermont','S');
INSERT INTO cc_partner_states VALUES ('VA','Virginia','S');
INSERT INTO cc_partner_states VALUES ('WA','Washington','S');
INSERT INTO cc_partner_states VALUES ('WV','West Virginia','S');
INSERT INTO cc_partner_states VALUES ('WI','Wisconsin','S');
INSERT INTO cc_partner_states VALUES ('WY','Wyoming','S');
INSERT INTO cc_partner_states VALUES ('AS','American Samoa','T');
INSERT INTO cc_partner_states VALUES ('GU','Guam','T');
INSERT INTO cc_partner_states VALUES ('PR','Puerto Rico','T');
INSERT INTO cc_partner_states VALUES ('VI','Virgin Islands','T');
